### ISSUE TITLE
A way to have multiple image sources and assign them to workers

### ISSUE THREAD

**Issue by Epikest** [r-PlaceTux/placetux-bot#28]
i'm not great at python, so here's my pseudocode:
```
images:
    tux: "https://tuximg.link",
    ally: "https://allyimg.link"
workers:
    tuxworker0:
        ...
        image: tux
    tuxworker1:
        ...
        image: tux
    allyworker0:
        ...
        image: ally
```
am on mobile so i can't look at the existing code
